version: '3.8'

services:
  sqlserver:
    build: .
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "123@Mudar"
      MSSQL_USER: "SA"
    ports:
      - "1433:1433"