CREATE TABLE wide_table (
    order_id VARCHAR(32),
    customer_id VARCHAR(32),
    customer_unique_id VARCHAR(32),
    customer_zip_code_prefix VARCHAR(7),
    customer_city VARCHAR(50),
    customer_state CHAR(2),
    order_status VARCHAR(20),
    order_purchase_timestamp DATETIME,
    order_approved_at DATETIME,
    order_delivered_carrier_date DATETIME,
    order_delivered_customer_date DATETIME,
    order_estimated_delivery_date DATE,
    order_item_id INT,
    product_id VARCHAR(32),
    product_category_name VARCHAR(50),
    product_name_length INT,
    product_description_length INT,
    product_photos_qty INT,
    product_weight_g INT,
    product_length_cm INT,
    product_height_cm INT,
    product_width_cm INT,
    seller_id VARCHAR(32),
    seller_zip_code_prefix VARCHAR(7),
    seller_city VARCHAR(50),
    seller_state CHAR(2),
    shipping_limit_date DATETIME,
    price DECIMAL(7, 2),
    freight_value DECIMAL(6, 2)
);
